### ISSUE TITLE
Critical bug: Consumer didn't build correctly/won't start

### ISSUE THREAD

**Issue by purple-emily** [Gabisonfire/knightcrawler#88]
The GitHub action has built the new consumer, but it will not start up.

```
consumer-1  | node:internal/modules/cjs/loader:1147
consumer-1  |   throw err;
consumer-1  |   ^
consumer-1  | 
consumer-1  | Error: Cannot find module '/app/dist/index.cjs'
consumer-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
consumer-1  |     at Module._load (node:internal/modules/cjs/loader:985:27)
consumer-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
consumer-1  |     at node:internal/main/run_main_module:28:49 {
consumer-1  |   code: 'MODULE_NOT_FOUND',
consumer-1  |   requireStack: []
consumer-1  | }
consumer-1  | 
consumer-1  | Node.js v20.11.1
consumer-1 exited with code 0
```

Using current code base:

```
  consumer:
    image: gabisonfire/knightcrawler-consumer:latest
    env_file:
      - .env
    deploy:
      replicas: ${CONSUMER_REPLICAS}
    <<: *knightcrawler-app
    networks:
      - knightcrawler-network
      - postgres-access
```

**Comment by purple-emily** [comment]
@sleeyax any input from you would be good too :)

**Comment by purple-emily** [comment]
I'm going to roll back the tag.

If you want to see the bug in action then you need to use the image: [sha-befd929](https://hub.docker.com/layers/gabisonfire/knightcrawler-consumer/sha-befd929/images/sha256-be035a3a476f94c128c9175c2204c142de24e980eabfa8fe3a9ba50c4c01a6be?context=explore)

`docker pull gabisonfire/knightcrawler-consumer:sha-befd929`

```
  consumer:
    image: gabisonfire/knightcrawler-consumer:sha-befd929
    env_file:
      - .env
    deploy:
      replicas: ${CONSUMER_REPLICAS}
    <<: *knightcrawler-app
    networks:
      - knightcrawler-network
      - postgres-access
```
